# Generated by Django 5.0.4 on 2024-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_poste_usr_alter_reaction_usr_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
