# Generated by Django 5.0.4 on 2024-04-28 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_poste_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenclub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='contactinfo',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='evensocial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='contactinfo',
        ),
        migrations.RemoveField(
            model_name='logement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='contactinfo',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='contactinfo',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='id',
        ),
        migrations.AddField(
            model_name='evenclub',
            name='evenement_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.evenement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenement',
            name='poste_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.poste'),
        ),
        migrations.AddField(
            model_name='evensocial',
            name='evenement_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.evenement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logement',
            name='poste_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.poste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommandation',
            name='poste_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.poste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='poste_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.poste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transport',
            name='poste_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.poste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poste',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='poste',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
