# Generated by Django 5.0.4 on 2024-04-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evenclub_id_remove_evenement_contactinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='poste_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.poste'),
        ),
    ]
