# Generated by Django 5.0.4 on 2024-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Student Help by MyDevify.com', max_length=100)),
                ('registration_open', models.BooleanField(default=True)),
            ],
        ),
    ]
